import { Injectable } from '@angular/core';
import { MovieInterface } from '../../utilities/interfaces/movie.interface';
import { GenreEnum } from '../../utilities/enums/genre.enum';
import { PeopleEnum } from '../../utilities/enums/people.enum';
import { CertificateEnum } from '../../utilities/enums/certificate.enum';

@Injectable({
  providedIn: 'root',
})
export class MoviesService {
  public moviesList: MovieInterface[] = [
    {
      title: 'Dune: Part Two',
      image: '../../../../assets/dune_part_2.jpg',
      trailer: 'https://www.youtube.com/watch?v=Way9Dexny3w',
      quality: '2D',
      desc: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
      certificate: CertificateEnum.PG_13,
      runtime: 166,
      genre: [GenreEnum.Action, GenreEnum.Adventure, GenreEnum.SciFi],
      director: [PeopleEnum.Denis_Villeneuve],
      cast: [
        PeopleEnum.Timothée_Chalamet,
        PeopleEnum.Zendaya,
        PeopleEnum.Rebecca_Ferguson,
        PeopleEnum.Javier_Bardem,
        PeopleEnum.Josh_Brolin,
        PeopleEnum.Austin_Butler,
        PeopleEnum.Florence_Pugh,
        PeopleEnum.Dave_Bautista,
        PeopleEnum.Léa_Seydoux,
      ],
      shows: [
        '9:00 - 11:46',
        '10:30 - 13:16',
        '11:30 - 14:16',
        '12:20 - 15:06',
        '13:00 - 15:46',
        '13:40 - 16:26',
        '14:20 - 17:06',
        '14:50 - 17:36',
        '15:30 - 18:16',
        '16:10 - 18:56',
        '16:40 - 19:26',
        '17:00 - 19:46',
        '17:30 - 20:16',
        '18:10 - 20:56',
        '18:50 - 21:36',
        '19:20 - 22:06',
        '19:40 - 22:26',
        '20:10- 22:56',
      ],
      price: 30,
    },
    {
      title: 'Furiosa: A Mad Max Saga',
      image: '../../../../assets/furiosa_a_mad_max_saga.jpg',
      trailer: 'https://www.youtube.com/watch?v=XJMuhwVlca4',
      quality: '2D',
      desc: 'The origin story of renegade warrior Furiosa before her encounter and teamup with Mad Max.',
      certificate: CertificateEnum.R,
      runtime: 148,
      genre: [GenreEnum.Action, GenreEnum.Adventure, GenreEnum.SciFi],
      director: [PeopleEnum.George_Miller],
      cast: [
        PeopleEnum.Anya_Taylor_Joy,
        PeopleEnum.Chris_Hemsworth,
        PeopleEnum.Tom_Burke,
        PeopleEnum.Alyla_Browne,
        PeopleEnum.George_Shevtsov,
        PeopleEnum.Lachy_Hulme,
        PeopleEnum.John_Howard,
        PeopleEnum.Angus_Sampson,
        PeopleEnum.Charlee_Fraser,
        PeopleEnum.Elsa_Pataky,
      ],
      shows: [
        '9:00 - 11:28',
        '9:50 - 12:18',
        '10:30 - 12:58',
        '11:20 - 13:48',
        '12:00 - 14:28',
        '12:40- 15:08',
        '13:20 - 15:48',
        '14:00 - 16:28',
        '14:50 - 17:18',
        '15:30 - 17:28',
        '16:50 - 19:18',
        '17:40 - 20:08',
        '18:20 - 20:48',
        '19:00 - 21:28',
        '19:50 - 22:18',
      ],
      price: 15,
    },
    {
      title: 'Inside Out 2',
      image: '../../../../assets/inside_out_2.jpg',
      desc: 'Follows Riley, in her teenage years, encountering new emotions.',
      certificate: CertificateEnum.PG,
      runtime: 96,
      genre: [GenreEnum.Animation, GenreEnum.Adventure, GenreEnum.Comedy],
      director: [PeopleEnum.Kelsey_Mann],
      cast: [
        PeopleEnum.Amy_Poehler,
        PeopleEnum.Maya_Hawke,
        PeopleEnum.Kensington_Tallman,
        PeopleEnum.Liza_Lapira,
        PeopleEnum.Tony_Hale,
        PeopleEnum.Lewis_Black,
        PeopleEnum.Phyllis_Smith,
        PeopleEnum.Ayo_Edebiri,
        PeopleEnum.Lilimar,
        PeopleEnum.Grace_Lu,
      ],
      shows: [
        '9:00 - 10:36',
        '11:00 - 12:36',
        '13:00 - 14:36',
        '14:30 - 16:06',
        '15:20 - 16:56',
        '15:50 - 17:26',
        '16:30 - 18:06',
        '17:00 - 18:36',
        '17:40 - 19:16',
        '18:10 - 19:46',
        '18:50 - 20:26',
        '19:20 - 20:56',
        '20:00 - 21:36',
        '21:20 - 22:56',
      ],
      price: 20,
    },
    {
      title: 'Kingdom of the Planet of the Apes',
      image: '../../../../assets/kingdom_of_the_planet_of_the_ape.jpg',
      desc: "Many years after the reign of Caesar, a young ape goes on a journey that will lead him to question everything he's been taught about the past and make choices that will define a future for apes and humans alike.",
      certificate: CertificateEnum.PG_13,
      runtime: 145,
      genre: [GenreEnum.Action, GenreEnum.Adventure, GenreEnum.Drama],
      director: [PeopleEnum.Wes_Ball],
      cast: [
        PeopleEnum.Owen_Teague,
        PeopleEnum.Freya_Allan,
        PeopleEnum.Kevin_Durand,
        PeopleEnum.Peter_Macon,
        PeopleEnum.William_H_Macy,
        PeopleEnum.Eka_Darville,
        PeopleEnum.Travis_Jeffery,
        PeopleEnum.Lydia_Peckham,
        PeopleEnum.Neil_Sandilands,
        PeopleEnum.Ras_Samuel,
      ],
    },
    {
      title: 'The Fall Guy',
      image: '../../../../assets/the_fall_guy.jpg',
      desc: "A down-and-out stuntman must find the missing star of his ex-girlfriend's blockbuster film.",
      certificate: CertificateEnum.PG_13,
      runtime: 126,
      genre: [GenreEnum.Action, GenreEnum.Comedy, GenreEnum.Drama],
      director: [PeopleEnum.David_Leitch],
      cast: [
        PeopleEnum.Ryan_Gosling,
        PeopleEnum.Emily_Blunt,
        PeopleEnum.Aaron_Taylor_Johnson,
        PeopleEnum.Hannah_Waddingham,
        PeopleEnum.Teresa_Palmer,
        PeopleEnum.Stephanie_Hsu,
        PeopleEnum.Winston_Duke,
        PeopleEnum.Ben_Knight,
        PeopleEnum.Matuse,
        PeopleEnum.Adam_Dunn,
      ],
    },
    {
      title: 'Monkey Man',
      image: '../../../../assets/monkey_man.jpg',
      desc: 'An anonymous young man unleashes a campaign of vengeance against the corrupt leaders who murdered his mother and continue to systematically victimize the poor and powerless.',
      certificate: CertificateEnum.R,
      runtime: 121,
      genre: [GenreEnum.Action, GenreEnum.Crime, GenreEnum.Thriller],
      director: [PeopleEnum.Dev_Patel],
      cast: [
        PeopleEnum.Dev_Patel,
        PeopleEnum.Pitobash,
        PeopleEnum.Jatin_Malik,
        PeopleEnum.Sikandar_Kher,
        PeopleEnum.Sobhita_Dhulipala,
        PeopleEnum.Makrand_Deshpande,
        PeopleEnum.Ashwini_Kalsekar,
        PeopleEnum.Vipin_Sharma,
        PeopleEnum.Adithi_Kalkunte,
      ],
    },
    {
      title: 'The Ministry of Ungentlemanly Warfare',
      image: '../../../../assets/the_ministry_of_ungentlemanly_warfare.jpg',
      desc: 'The British military recruits a small group of highly skilled soldiers to strike against German forces behind enemy lines during World War II.',
      certificate: CertificateEnum.R,
      runtime: 120,
      genre: [GenreEnum.Action, GenreEnum.Drama, GenreEnum.War],
      director: [PeopleEnum.Guy_Ritchie],
      cast: [
        PeopleEnum.Henry_Cavill,
        PeopleEnum.Alan_Ritchson,
        PeopleEnum.Alex_Pettyfer,
        PeopleEnum.Eiza_González,
        PeopleEnum.Babs_Olusanmokun,
        PeopleEnum.Cary_Elwes,
        PeopleEnum.Hero_Fiennes_Tiffin,
        PeopleEnum.Henry_Golding,
        PeopleEnum.Rory_Kinnear,
        PeopleEnum.Til_Schweiger,
      ],
    },
    {
      title: 'A Quiet Place: Day One',
      image: '../../../../assets/a_quiet_place_day_one.jpg',
      desc: 'A woman named Sam finds herself trapped in New York City during the early stages of an invasion by alien creatures with ultrasonic hearing',
      certificate: CertificateEnum.PG_13,
      runtime: 100,
      genre: [GenreEnum.Drama, GenreEnum.Horror, GenreEnum.SciFi],
      director: [PeopleEnum.Michael_Sarnoski],
      cast: [
        PeopleEnum.Joseph_Quinn,
        PeopleEnum.Lupita_Nyongo,
        PeopleEnum.Alex_Wolff,
        PeopleEnum.Djimon_Hounsou,
        PeopleEnum.Thea_Butler,
        PeopleEnum.Jennifer_Woodward,
        PeopleEnum.Sunjay_Midda,
        PeopleEnum.Elijah_Ungvary,
        PeopleEnum.Zay_Domo_Artist,
        PeopleEnum.Cain_Aiden,
      ],
    },
    {
      title: 'Despicable Me 4',
      image: '../../../../assets/despicable_me_4.jpg',
      desc: 'Gru, Lucy, Margo, Edith, and Agnes welcome a new member to the family, Gru Jr., who is intent on tormenting his dad. Gru faces a new nemesis in Maxime Le Mal and his girlfriend Valentina, and the family is forced to go on the run.',
      certificate: CertificateEnum.PG,
      runtime: 95,
      genre: [GenreEnum.Animation, GenreEnum.Adventure, GenreEnum.Comedy],
      director: [PeopleEnum.Chris_Renaud, PeopleEnum.Patrick_Delage],
      cast: [
        PeopleEnum.Steve_Carell,
        PeopleEnum.Kristen_Wiig,
        PeopleEnum.Joey_King,
        PeopleEnum.Will_Ferrell,
        PeopleEnum.Sofía_Vergara,
        PeopleEnum.Miranda_Cosgrove,
        PeopleEnum.Dana_Gaier,
        PeopleEnum.Madison_Skyy_Polan,
        PeopleEnum.Pierre_Coffin,
        PeopleEnum.Steve_Coogan,
      ],
    },
    {
      title: 'Joker: Folie à Deux',
      image: '../../../../assets/joker_folie_à_deux.jpg',
      desc: 'Sequel to the film "Joker" from 2019.',
      certificate: CertificateEnum.R,
      runtime: 120,
      genre: [GenreEnum.Crime, GenreEnum.Drama, GenreEnum.Musical],
      director: [PeopleEnum.Todd_Phillips],
      cast: [
        PeopleEnum.Joaquin_Phoenix,
        PeopleEnum.Lady_Gaga,
        PeopleEnum.Zazie_Beetz,
        PeopleEnum.Catherine_Keener,
        PeopleEnum.Brendan_Gleeson,
        PeopleEnum.Steve_Coogan,
        PeopleEnum.Ken_Leung,
        PeopleEnum.Jacob_Lofland,
        PeopleEnum.Gattlin_Griffith,
        PeopleEnum.Bill_Smitrovich,
      ],
    },
    {
      title: 'Deadpool & Wolverine',
      image: '../../../../assets/dp&w.jpg',
      desc: 'Wolverine is recovering from his injuries when he crosses paths with the loudmouth Deadpool. They team up to defeat a common enemy.',
      certificate: CertificateEnum.R,
      runtime: 127,
      genre: [GenreEnum.Action, GenreEnum.Comedy, GenreEnum.SciFi],
      director: [PeopleEnum.Shawn_Levy],
      cast: [
        PeopleEnum.Ryan_Reynolds,
        PeopleEnum.Hugh_Jackman,
        PeopleEnum.Emma_Corrin,
      ],
    },
    {
      title: 'Gladiator 2',
      image: '../../../../assets/gladiator_2.jpg',
      desc: "Follows Lucius, the son of Maximus's love Lucilla, after Maximus's death.",
      certificate: CertificateEnum.R,
      runtime: 156,
      genre: [GenreEnum.Action, GenreEnum.Adventure, GenreEnum.Drama],
      director: [PeopleEnum.Ridley_Scott],
      cast: [
        PeopleEnum.Denzel_Washington,
        PeopleEnum.Pedro_Pascal,
        PeopleEnum.Joseph_Quinn,
        PeopleEnum.Connie_Nielsen,
        PeopleEnum.Paul_Mescal,
        PeopleEnum.Rory_McCann,
        PeopleEnum.Fred_Hechinger,
        PeopleEnum.Derek_Jacobi,
        PeopleEnum.Matt_Lucas,
        PeopleEnum.Tim_McInnerny,
      ],
    },
    {
      title: 'Kraven the Hunter',
      image: '../../../../assets/kraven_the_hunter.jpg',
      desc: 'Russian immigrant Sergei Kravinoff is on a mission to prove that he is the greatest hunter in the world.',
      certificate: CertificateEnum.PG,
      runtime: 110,
      genre: [GenreEnum.Action, GenreEnum.Adventure, GenreEnum.SciFi],
      director: [PeopleEnum.JC_Chandor],
      cast: [
        PeopleEnum.Aaron_Taylor_Johnson,
        PeopleEnum.Russell_Crowe,
        PeopleEnum.Ariana_DeBose,
        PeopleEnum.Fred_Hechinger,
        PeopleEnum.Christopher_Abbott,
        PeopleEnum.Alessandro_Nivola,
        PeopleEnum.Levi_Miller,
        PeopleEnum.Al_Nedjari,
        PeopleEnum.Elander_Moore,
        PeopleEnum.Duran_Fulton_Brown,
      ],
    },
    {
      title: 'Nosferatu',
      image: '../../../../assets/nosferatu.jpg',
      desc: 'A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.',
      certificate: CertificateEnum.R,
      runtime: 133,
      genre: [GenreEnum.Fantasy, GenreEnum.Horror, GenreEnum.Mystery],
      director: [PeopleEnum.Robert_Eggers],
      cast: [
        PeopleEnum.Aaron_Taylor_Johnson,
        PeopleEnum.Bill_Skarsgård,
        PeopleEnum.Willem_Dafoe,
        PeopleEnum.Nicholas_Hoult,
        PeopleEnum.Emma_Corrin,
        PeopleEnum.Ralph_Ineson,
        PeopleEnum.LilyRose_Depp,
        PeopleEnum.Simon_McBurney,
        PeopleEnum.Paul_A_Maynard,
        PeopleEnum.Stacy_Thunes,
      ],
    },
    {
      title: 'Kinds of Kindness',
      image: '../../../../assets/kinds_of_kindness.jpg',
      desc: "A man seeks to break free from his predetermined path, a cop questions his wife's demeanor after her return from a supposed drowning, and a woman searches for an extraordinary individual prophesied to become a renowned spiritual guide.",
      certificate: CertificateEnum.R,
      runtime: 164,
      genre: [GenreEnum.Comedy, GenreEnum.Drama],
      director: [PeopleEnum.Yorgos_Lanthimos],
      cast: [
        PeopleEnum.Emma_Stone,
        PeopleEnum.Jesse_Plemons,
        PeopleEnum.Willem_Dafoe,
        PeopleEnum.Margaret_Qualley,
        PeopleEnum.Hong_Chau,
        PeopleEnum.Joe_Alwyn,
        PeopleEnum.Mamoudou_Athie,
        PeopleEnum.Hunter_Schafer,
        PeopleEnum.Yorgos_Stefanakos,
        PeopleEnum.Merah_Benoit,
      ],
    },
    {
      title: 'Borderlands',
      image: '../../../../assets/borderlands.jpg',
      desc: 'Based on the best-selling videogame, this all-star action-adventure follows a ragtag team of misfits on a mission to save a missing girl who holds the key to unimaginable power.',
      certificate: CertificateEnum.PG_13,
      runtime: 102,
      genre: [GenreEnum.Action, GenreEnum.Adventure, GenreEnum.Comedy],
      director: [PeopleEnum.Eli_Roth],
      cast: [
        PeopleEnum.Gina_Gershon,
        PeopleEnum.Cate_Blanchett,
        PeopleEnum.Haley_Bennett,
        PeopleEnum.Kevin_Hart,
        PeopleEnum.Ariana_Greenblatt,
        PeopleEnum.Jack_Black,
        PeopleEnum.Jamie_Lee_Curtis,
        PeopleEnum.Edgar_Ramírez,
        PeopleEnum.Janina_Gavankar,
        PeopleEnum.Bobby_Lee,
      ],
    },
    {
      title: 'Transformers One',
      image: '../../../../assets/transformers_one.jpg',
      desc: 'The untold origin story of Optimus Prime and Megatron, better known as sworn enemies, but once were friends bonded like brothers who changed the fate of Cybertron forever.',
      certificate: CertificateEnum.PG_13,
      runtime: 90,
      genre: [GenreEnum.Animation, GenreEnum.Action, GenreEnum.Adventure],
      director: [PeopleEnum.Josh_Cooley],
      cast: [
        PeopleEnum.Chris_Hemsworth,
        PeopleEnum.Brian_Tyree_Henry,
        PeopleEnum.Scarlett_Johansson,
        PeopleEnum.KeeganMichael_Key,
        PeopleEnum.Jon_Hamm,
        PeopleEnum.Laurence_Fishburne,
        PeopleEnum.Steve_Buscemi,
      ],
    },
  ];

  constructor() {}

  public getMovie(): MovieInterface[] {
    return this.moviesList;
  }
}
